"""fix tables

Revision ID: 405a38fd4a61
Revises: abcebccc5175
Create Date: 2026-01-01 08:24:43.038451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405a38fd4a61'
down_revision: Union[str, Sequence[str], None] = 'abcebccc5175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('author_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_Books_authoer_id'), table_name='Books')
    op.create_index(op.f('ix_Books_author_id'), 'Books', ['author_id'], unique=False)
    op.drop_constraint(op.f('Books_authoer_id_fkey'), 'Books', type_='foreignkey')
    op.create_foreign_key(None, 'Books', 'Authors', ['author_id'], ['id'])
    op.drop_column('Books', 'authoer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('authoer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.create_foreign_key(op.f('Books_authoer_id_fkey'), 'Books', 'Authors', ['authoer_id'], ['id'])
    op.drop_index(op.f('ix_Books_author_id'), table_name='Books')
    op.create_index(op.f('ix_Books_authoer_id'), 'Books', ['authoer_id'], unique=False)
    op.drop_column('Books', 'author_id')
    # ### end Alembic commands ###
