"""change not null

Revision ID: 712460a1f8bb
Revises: 405a38fd4a61
Create Date: 2026-01-04 13:30:00.234359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712460a1f8bb'
down_revision: Union[str, Sequence[str], None] = '405a38fd4a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Books', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Books', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
